dentist/urls.py
from django.conf.urls import url
from django.contrib import admin
from dentist_app import views
from django.conf.urls import url, include
from accounts import views as accounts_views
from services import views as service_views
from appointments import views as appointment_views
from django.conf import settings
from django.views.static import serve
from blog import views as blog_views
from threads import views as forum_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.get_index, name='index'),
    url(r'^ourteam/$', views.get_ourteam, name='ourteam'),
    url(r'^contact/$', views.get_contact, name='contact'),
    url(r'^contact_thanks/$', views.get_contact_thanks, name='contact_thanks'),
    #Authentication URLs
    url(r'^membership/$', accounts_views.register, name='register'),
    url(r'^profile/$', accounts_views.profile, name='profile'),
    url(r'^login/$', accounts_views.login, name='login'),
    url(r'^logout/$', accounts_views.logout, name='logout'),
    url(r'^cancel_subscription/$', accounts_views.cancel_subscription, name='cancel_subscription'),
    url(r'^family_members/$', accounts_views.family_member_details, name='family_member_details'),
    url(r'^families/$', accounts_views.all_families, name='families'),
    url(r'^success/$', accounts_views.success, name='success'),

    #Blog URLs
    url(r'^blog/$', blog_views.post_list, name="post_list"),
    url(r'^blog/(?P<id>\d+)/$', blog_views.post_detail),


    #Media URLs
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),

    #Services URLs
    url(r'^services/$', service_views.all_services, name='services'),

    #Appointments URLs
    url(r'^appointments/$', appointment_views.get_user_appointments, name='appointments'),
    url(r'^create_appointment/$', appointment_views.create_appointment, name='create_appointment'),

    # Forum URLs
    url(r'^forum/$', forum_views.forum, name="forum"),
    url(r'^threads/(?P<subject_id>\d+)/$', forum_views.threads, name='threads'),
    url(r'^new_thread/(?P<subject_id>\d+)/$',  forum_views.new_thread, name='new_thread'),
    url(r'^thread/(?P<thread_id>\d+)/$', forum_views.thread, name='thread'),
    url(r'^post/new/(?P<thread_id>\d+)/$', forum_views.new_post, name='new_post'),
    url(r'^post/edit/(?P<thread_id>\d+)/(?P<post_id>\d+)/$',forum_views.edit_post, name='edit_post'),
    url(r'^post/delete/(?P<thread_id>\d+)/(?P<post_id>\d+)/$', forum_views.delete_post, name='delete_post'),
    url(r'^thread/vote/(?P<thread_id>\d+)/(?P<subject_id>\d+)/$', forum_views.thread_vote, name='cast_vote'),


]

threads/models.py
from django.db import models
from django.utils import timezone
from tinymce.models import HTMLField
from django.conf import settings
from django.utils.html import mark_safe


class Subject(models.Model):
    name = models.CharField(max_length=255)
    description = HTMLField()

    def __unicode__(self):
        return self.name


class Thread(models.Model):
    name = models.CharField(max_length=255)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='threads')
    subject = models.ForeignKey(Subject, related_name='threads')
    created_at = models.DateTimeField(default=timezone.now())

    def __unicode__(self):
        return self.name


class Post(models.Model):
    thread = models.ForeignKey(Thread, related_name='posts')
    comment = HTMLField(blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='posts')
    created_at = models.DateTimeField(default=timezone.now())

    def __unicode__(self):
        return mark_safe(self.comment[0:50])

threads/forms.py
from django import forms
from .models import Thread, Post


class ThreadForm(forms.ModelForm):
    name = forms.CharField(label="Thread name")
    is_a_poll = forms.BooleanField(label="Include a poll?", required=False)

    class Meta:
        model = Thread
        fields = ['name']


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['comment']

threads/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.shortcuts import render, get_object_or_404
from django.contrib import messages, auth
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.template.context_processors import csrf
from .forms import ThreadForm, PostForm
from threads.models import Subject, Post, Thread
from django.forms import formset_factory
from polls.forms import PollSubjectForm, PollForm
from polls.models import PollSubject


def forum(request):
    return render(request, 'forum/forum.html', {'subjects': Subject.objects.all()})


def threads(request, subject_id):
    subject = get_object_or_404(Subject, pk=subject_id)
    return render(request, 'forum/threads.html', {'subject': subject})


@login_required
def new_thread(request, subject_id):
    subject = get_object_or_404(Subject, pk=subject_id)

    poll_subject_formset = formset_factory(PollSubjectForm, extra=3)

    if request.method == "POST":
        thread_form = ThreadForm(request.POST)
        post_form = PostForm(request.POST)
        poll_form = PollForm(request.POST)
        poll_subject_formset = poll_subject_formset(request.POST)

        if request.POST.get('is_a_poll', None):

            # save thread with the poll
            if thread_form.is_valid() and post_form.is_valid() and poll_form.is_valid() and poll_subject_formset.is_valid():
                thread = thread_form.save(False)
                thread.subject = subject
                thread.user = request.user
                thread.save()

                post = post_form.save(False)
                post.user = request.user
                post.thread = thread
                post.save()

                poll = poll_form.save(False)
                poll.thread = thread
                poll.save()

                for subject_form in poll_subject_formset:
                    subject = subject_form.save(False)
                    subject.poll = poll
                    subject.save()

                messages.success(request, "You have created a new thread!")

                return redirect(reverse('thread', args={thread.pk}))
        else:
            # save thread without a poll
            if thread_form.is_valid() and post_form.is_valid() and poll_subject_formset.is_valid():
                thread = thread_form.save(False)
                thread.subject = subject
                thread.user = request.user
                thread.save()

                post = post_form.save(False)
                post.user = request.user
                post.thread = thread
                post.save()

                messages.success(request, "You have created a new thread!")

                return redirect(reverse('thread', args={thread.pk}))

    else:
        thread_form = ThreadForm()
        post_form = PostForm(request.POST)
        poll_form = PollForm()
        poll_subject_formset = poll_subject_formset()

    args = {
        'thread_form': thread_form,
        'post_form': post_form,
        'subject': subject,
        'poll_form': poll_form,
        'poll_subject_formset': poll_subject_formset,
    }

    args.update(csrf(request))

    return render(request, 'forum/thread_form.html', args)


def thread(request, thread_id):
    thread_ = get_object_or_404(Thread, pk=thread_id)
    args = {'thread': thread_}
    args.update(csrf(request))
    return render(request, 'forum/thread.html', args)


@login_required
def new_post(request, thread_id):
    thread = get_object_or_404(Thread, pk=thread_id)

    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(False)
            post.thread = thread
            post.user = request.user
            post.save()

            messages.success(request, "Your post has been added to the thread!")

            return redirect(reverse('thread', args={thread.pk}))
    else:
        form = PostForm()

    args = {
        'form': form,
        'form_action': reverse('new_post', args={thread.id}),
        'button_text': 'Update Post'
    }
    args.update(csrf(request))

    return render(request, 'forum/post_form.html', args)


@login_required
def edit_post(request, thread_id, post_id):
    thread = get_object_or_404(Thread, pk=thread_id)
    post = get_object_or_404(Post, pk=post_id)

    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            messages.success(request, "You have updated your thread!")

            return redirect(reverse('thread', args={thread.pk}))
    else:
        form = PostForm(instance=post)

    args = {
        'form': form,
        'form_action': reverse('edit_post', kwargs={"thread_id": thread.id, "post_id": post.id}),
        'button_text': 'Update Post'
    }
    args.update(csrf(request))

    return render(request, 'forum/post_form.html', args)


@login_required
def delete_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    thread_id = post.thread.id
    post.delete()

    messages.success(request, "Your post was deleted!")

    return redirect(reverse('thread', args={thread_id}))


@login_required
def thread_vote(request, thread_id, subject_id):
    thread = Thread.objects.get(id=thread_id)

    subject = thread.poll.votes.filter(user=request.user)

    if subject:
        messages.error(request, "You've already voted on this poll!")
        return redirect(reverse('thread', args={thread_id}))

    subject = PollSubject.objects.get(id=subject_id)

    subject.votes.create(poll=subject.poll, user=request.user)

    messages.success(request, "We've registered your vote!")

    return redirect(reverse('thread', args={thread_id}))

templates/forum/comment_details.html
{% load thread_extras %}
<div class="details">
   <div class="col-md-6">
       <div class="pull-left">
           <time datetime="{{ post.created_at }}">
              Posted: {{ post.created_at|started_time }}
           </time>
       </div>
   </div>
   <div class="col-md-6">
       <div class="pull-right">
         {% if post.user == user or user.is_staff %}
           <a href="{% url 'edit_post' thread.id post.id %}"><i class="fa fa-pencil-square-o"></i></a>
           <a href="{% url 'delete_post' thread.id post.id %}"><i class="fa fa-trash-o"></i></a>
         {% endif %}
       </div>
   </div>
   <div class="clearfix"></div>
</div>

templates/forum/forum.html
{% extends "forum/forumbase.html" %}
{% load thread_extras %}

{% block forumtitle %}
<div class="wrap">
<div class="container home-apoint">
<div class="row">
<div class="col-md-12 home-apoint-text">
<h2>Forum</h2>
</div>
</div><!--end row-->
</div><!--end container-->
</div><!--end wrap-->
{% endblock %}

{% block forumcontent %}
<div class="container">
<ol class="breadcrumb pull-left where-am-i">
      <li>Forum</li>
      <li class="active">Categories</li>
    </ol>
</div>
<div>

  <table class="table forum table-striped">
    <thead>
      <tr>
        <th class="cell-stat"></th>
        <th>
          <h3>Forum Categories</h3>
        </th>
        <th class="cell-stat text-center hidden-xs hidden-sm">Threads</th>
        <th class="cell-stat text-center hidden-xs hidden-sm">Posts</th>
        <th class="cell-stat-2x hidden-xs hidden-sm">Last Post</th>
      </tr>
    </thead>
    <tbody>

        {% for subject in subjects %}


      <tr>
        <td class="text-center"><i class="fa fa-question fa-2x text-primary"></i></td>
        <td>
          <h4><a href="{% url "threads" subject.id %}">{{ subject.name }}</a></h4>
          <h6>{% autoescape off %}{{ subject.description }}{% endautoescape %}</h6>
        </td>
        <td class="text-center hidden-xs hidden-sm">{{ subject.threads.count }}</td>
        <td class="text-center hidden-xs hidden-sm">{{ subject|get_total_subject_posts }}</td>
        <td class="hidden-xs hidden-sm">by <a href="#">John Doe</a><br><small><i class="fa fa-clock-o"></i> 3 months ago</small></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
<hr/>
</div>

{% endblock %}

templates/forum/forumbase.html
{% extends "base.html" %}

{% block content %}

    {% block forumtitle %}
    {% endblock %}


<div class="wrap margin-block">
<div class="container">
<div class="row">

    {% block forumcontent %}
    {% endblock %}


</div><!--end row-->

</div><!--end container-->
</div><!--end wrap-->

{% endblock %}

templates/forum/post.html
{% load staticfiles %}
{% load emoticons_tags %}
{% load thread_extras %}
{% load gravatar %}
<section class="row comment col-md-9">
 <div class="col-md-3 comment-profile">
   <p><img src="{% gravatar_url post.user_id.email 100 %}" /></p>
   <p>{% get_poster_name post %}</p>
   <p>{{ post.user.posts.count }} POSTS</p>
 </div>
 <div class="col-md-9 ">
   <div class="comment-content">
     {% autoescape off %}
       {{ post.comment|emoticons }}
     {% endautoescape %}
   </div>
   {% include "forum/comment_details.html" %}
 </div>

</section>

templates/forum/post_form.html
{% extends "forum/forumbase.html" %}
{% load bootstrap_tags %}
{% load staticfiles %}
{% load thread_extras %}

{% block head_js %}
<script src="{% static 'js/tinymce/tinymce.min.js' %}"></script>
<script type="text/javascript">
 tinyMCE.init({
   mode: "textareas",
   theme: "modern",
   plugins: "paste",
});
</script>
{% endblock %}

{% block forumtitle %}
<div class="wrap">
<div class="container home-apoint">
<div class="row">
<div class="col-md-12 home-apoint-text">
<h2>Forum</h2>
</div>
</div><!--end row-->
</div><!--end container-->
</div><!--end wrap-->
{% endblock %}


{% block forumcontent %}
<div class="container">
<ol class="breadcrumb pull-left where-am-i">
    <li><a href="javascript:history.back()">Back to Thread</a></li>

    </ol>
</div>
<br/>
<div class="container">
       <div class="col-md-9">
     <form method="post" action="{{ form_action }}">
       {% csrf_token %}
       {{ form|as_bootstrap }}
       <div class="form-group">
         <button type="submit" class="btn btn-primary">{{button_text}}</button>
       </div>
     </form>
   </div>
</div>
{% endblock %}

templates/forum/thread.html
{% extends "forum/forumbase.html" %}
{% load bootstrap_tags %}
{% load staticfiles %}
{% load thread_extras %}



{% block head_js %}
   <script type="text/javascript" src="{% static 'js/tinymce/tinymce.min.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
   <script type="application/javascript">
       tinyMCE.init({mode: "textareas", theme: 'modern', plugins: 'paste'})

   </script>
{% endblock %}

{% block forumtitle %}
<div class="wrap">
<div class="container home-apoint">
<div class="row">
<div class="col-md-12 home-apoint-text">
<h2>Forum</h2>
</div>
</div><!--end row-->
</div><!--end container-->
</div><!--end wrap-->
{% endblock %}


{% block forumcontent %}
<div class="container">
<ol class="breadcrumb pull-left where-am-i">
    <li><a href="/forum/">Forum</a></li>
    <li><a href="{% url 'threads' thread.subject.id %}">{{ thread.subject.name }}</a></li>
    <li class="active">{{ thread.name }}</li>
</ol>
</div>
<br/>
<div class="container">

        {% if thread.poll %}

           <div class="container">

               <div class="col-md-8 thread-box">
                   <h3>{{ thread.name }}</h3>
                <hr>
                   {% for post in thread.posts.all %}
                    {% include "forum/post.html" %}
                    {% endfor %}
               </div>

               <div class="col-md-4 poll-box">
                   <h3>Poll</h3>
                   <strong>{{ thread.poll.question }}</strong><br><br>

                   <p>Here’s how the votes are so far:</p>
                 {% for subject in thread.poll.subjects.all %}
                       <div class="col-md-10">
                           <strong>{{ subject.name }}</strong>
                           <span class="pull-right">{{ subject|vote_percentage }}%</span>
                       </div>
                       {% user_vote_button thread subject user %}
                    <div class="col-md-10">
                     <div class="progress">
                       <div class="progress-bar progress-bar-info" role="progressbar"
                        aria-value="{{ subject|vote_percentage }}" aria-valuemin="0"
                        aria-valuemax="100" style="width:{{ subject|vote_percentage }}%;">
                       </div>
                     </div>
                    </div>
                  {% endfor %}
               </div>
           </div>
        {% else %}
            <div class="container">

               <div class="col-md-12 thread-box">
                   <h3>{{ thread.name }}</h3>
                <hr>
                   {% for post in thread.posts.all %}
                    {% include "forum/post.html" %}
                    {% endfor %}
               </div>


           </div>
       {% endif %}

     {% if user.is_authenticated %}
       <p>
         <a href="{% url 'new_post' thread.id %}" class="btn btn-primary">New post</a>
       </p>
     {% endif %}
   </div>


{% endblock %}

templates/forum/thread_form.html
{% extends "forum/forumbase.html" %}
{% load bootstrap_tags %}
{% load staticfiles %}
{% load thread_extras %}



{% block head_js %}
   <script type="text/javascript" src="{% static 'js/tinymce/tinymce.min.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
   <script type="application/javascript">
       tinyMCE.init({mode: "textareas", theme: 'modern', plugins: 'paste'})

   </script>
{% endblock %}

{% block forumtitle %}
<div class="wrap">
<div class="container home-apoint">
<div class="row">
<div class="col-md-12 home-apoint-text">
<h2>Forum</h2>
</div>
</div><!--end row-->
</div><!--end container-->
</div><!--end wrap-->
{% endblock %}


{% block forumcontent %}
<div class="container">
<ol class="breadcrumb pull-left where-am-i">
    <li><a href="/forum/">Forum</a></li>
    <li><a href="{% url 'threads' subject.id %}">{{ subject.name }}</a></li>
    <li class="active">New Thread</li>

    </ol>
</div>
<br/>
<div class="container">
       <div class="col-md-9">
           <form method="post" action="{% url 'new_thread' subject.id %}">
               {% csrf_token %}
               <div class="form-group">
                   {{ thread_form | as_bootstrap }}
                   <hr>
                   {{ post_form | as_bootstrap }}
               </div>
               <div id="poll_form" class="form-group">
                   {{ poll_form|as_bootstrap }}
                   {{ poll_subject_formset.management_form }}
                   {% for poll_subject_form in poll_subject_formset %}
                       {{ poll_subject_form|as_bootstrap }}
                   {% endfor %}
               </div>
               <div class="form-group">
                   <button type="submit" class="btn-primary"> Post New Thread</button>
               </div>
           </form>
       </div>

</div>
  <!-- JQuery Stuff to go in here -->
    <script>
    $(function() {
        if (!$('#id_is_a_poll').is('checked')) {
            $('#poll_form').hide()
        }

        $('#id_is_a_poll').click(function(el) {
            var poll_form = $('#poll_form')

            if (poll_form.is(":visible")) {
                poll_form.hide()
            } else {
                poll_form.show()
            }
        })
    })
    </script>
{% endblock %}

templates/forum/thread_item.html
<tr>
        <td class="text-center"><i class="fa fa-question fa-2x text-primary"></i></td>
        <td>
          <h4><a href="{% url "thread" thread.id %}">{{ thread.name }}</a></h4>
        </td>

        <td class="text-center hidden-xs hidden-sm">Total Posts</td>
        <td class="hidden-xs hidden-sm">by <a href="#">John Doe</a><br><small><i class="fa fa-clock-o"></i> 3 months ago</small></td>
      </tr>

templates/forum/threads.html
{% extends "forum/forumbase.html" %}
{% load thread_extras %}

{% block forumtitle %}
<div class="wrap">
<div class="container home-apoint">
<div class="row">
<div class="col-md-12 home-apoint-text">
<h2>Forum</h2>
</div>
</div><!--end row-->
</div><!--end container-->
</div><!--end wrap-->
{% endblock %}

{% block forumcontent %}
<div class ="container">
<ol class="breadcrumb pull-left where-am-i">
    <li><a href="/forum/">Forum</a></li>
    <li class="active">{{ subject.name }}</li>
    <!--<li><a href="{% url 'threads' subject.id %}">{{ subject.name }}</a></li>-->

    </ol>
</div>
<div class="container">


    {% if user.is_authenticated %}
        <p>
            <a href="{% url 'new_thread' subject.id %}" class="btn btn-info">New Thread</a>
        </p>
    {% endif %}

</div>


<div>

  <table class="table forum table-striped">
    <thead>
      <tr>
        <th class="cell-stat"></th>
        <th>
          <h3>{{ subject.name }}</h3>
        </th>
        <th class="cell-stat text-center hidden-xs hidden-sm">Posts</th>
        <th class="cell-stat-2x hidden-xs hidden-sm">Last Post</th>
      </tr>
    </thead>
    <tbody>

        {% for thread in subject.threads.all %}
        {% include "forum/thread_item.html" %}
      {% endfor %}


    </tbody>
  </table>

<hr/>
</div>

{% endblock %}